title: Temporal changes in catch sizes
description: This dataseat feature catch volumes recollected by Sainte-Marie fishermen, along with years, fisher IDs, and fishing gear.

publisher_text: PLOS ONE
publisher_url: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0259792

license_text: 
license_url: 

frequency: 

certificate_embed: 
